services:
  ghetto-bsky-api:
    env_file: .env
    container_name: ghetto-bsky-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - ghetto-bsky-backend

networks:
  ghetto-bsky-backend:
